### ISSUE TITLE
search on homepage

### ISSUE THREAD

**Issue by story645** [matplotlib/mpl-brochure-site#50]
Can we add a search bar in the upper right corner (or really anywhere?) - I get the concerns about clutter, but lately 99% of my interactions have been homepage->docs->search 'cause I keep forgetting that there's no search on the homepage. 
![image](https://user-images.githubusercontent.com/1300499/168185957-e127cf50-ebce-42d1-b81c-1f5c035f054f.png)

**Comment by timhoffm** [comment]
If possible, I'd prefer that the search bar is in the same position for the cover page (https://matplotlib.org/) and for the individual doc pages.

Since the cover page has no sidebar, it would be reasonable to put it in the navbar (if there is enough space).
It looks like the pydata-sphinx-theme [has an option for that](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#configure-the-search-bar-position). IMHO that should be the first thing to check.

**Comment by story645** [comment]
Agree, and that would mean a PR on https://github.com/matplotlib/mpl-sphinx-theme but not sure if I should transfer this issue there so I added it to the call agenda

**Comment by story645** [comment]
Yup, but if I change the configuration than the search bar location will change on all the pages. As far as I know the front page doesn't have a sidebar and that's why it doesn't have a search bar.

**Comment by timhoffm** [comment]
The front page has no sidebar. IMHO we should do this:

Move the search bar to the navbar using the above mentioned option. This is a already a config option of mpl-sphinx-theme, so does not need any change/PR on their side.

AFAICS this could be done in the same way on our normal docs and the brochure site.

**Comment by timhoffm** [comment]
Style:
The search field should be on the right next to the link icons. For this the version switcher should be moved next to the logo, its dev entry should be shortened.

Current:
![grafik](https://user-images.githubusercontent.com/2836374/170527394-bf4529aa-32f8-4e0f-be88-064e1a905b7b.png)

Suggested:
![grafik](https://user-images.githubusercontent.com/2836374/170528587-60b285ba-69ed-48b6-af47-fab1293a9418.png)
